# Generated by Django 5.0.3 on 2024-06-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoboBrain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'managed': False, 'verbose_name_plural': 'Abonnoment'},
        ),
        migrations.AlterModelOptions(
            name='aflevering',
            options={'managed': False, 'verbose_name_plural': 'Aflevering'},
        ),
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': False, 'verbose_name_plural': 'AuthGroup'},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': False, 'verbose_name_plural': 'AuthGroupPermission'},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': False, 'verbose_name_plural': 'AuthPermission'},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False, 'verbose_name_plural': 'AuthUser'},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': False, 'verbose_name_plural': 'AuthUserGroups'},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': False, 'verbose_name_plural': 'AuthUserUserPermissions'},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': False, 'verbose_name_plural': 'DjangoMigrations'},
        ),
        migrations.AlterModelOptions(
            name='klant',
            options={'managed': False, 'verbose_name_plural': 'Klant'},
        ),
        migrations.AlterModelOptions(
            name='seizoen',
            options={'managed': False, 'verbose_name_plural': 'Seizoen'},
        ),
        migrations.AlterModelOptions(
            name='stream',
            options={'managed': False, 'verbose_name_plural': 'Stream'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name_plural': 'Users'},
        ),
    ]
